version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - "./data/db1/mysql:/var/lib/mysql"
      - "./data/db1/conf:/etc/mysql/conf.d"
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: 
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    command: --wsrep-new-cluster
    networks:
      galeranet:
        ipv4_address: 192.168.128.2

networks:
  galeranet:
    external: true
    name: galeranet
